## docker-compose.yml.

## Common parameters.
# Flask app common parameters.
x-flask-app-common: &flask-app-common
  build:
    context: .
    dockerfile: ./dockerfiles/Dockerfile.app
  container_name: flask_app
  depends_on:
    - postgres
  expose:
    - "5000"
  restart: always

# Nginx server common parameters.
x-nginx-common: &nginx-common
  build:
    context: .
    dockerfile: ./dockerfiles/Dockerfile.nginx
  container_name: nginx_server
  restart: always

## Services.
services:
  
  ## Flask app service.
  # Development parameters.
  flask-app-dev:
    <<: *flask-app-common
    env_file:
      - ./environment/flask_common.env
      - ./environment/flask_dev.env
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app
    profiles:
      - dev

  # Production parameters.
  flask-app-prod:
    <<: *flask-app-common
    env_file:
      - ./environment/flask_common.env
      - ./environment/flask_prod.env
    profiles:
      - prod

  ## Nginx service.
  # Development parameters.
  nginx-dev:
    <<: *nginx-common
    depends_on:
      - flask-app-dev
    env_file:
      - ./environment/nginx_common.env
      - ./environment/nginx_dev.env
    ports:
      - "5000:80"
    develop:
      watch:
        - action: sync+restart
          path: ./config/nginx.conf
          target: /etc/nginx/nginx.conf
        - action: sync+restart
          path: ./config/default.conf
          target: /etc/nginx/conf.d/default.conf
    profiles:
      - dev

  # Production parameters.
  nginx-prod:
    <<: *nginx-common
    depends_on:
      - flask-app-prod
    env_file:
      - ./environment/nginx_common.env
      - ./environment/nginx_prod.env
    ports:
      - "80:80"
    profiles:
      - prod

  ## PostgreSQL service.
  postgres:
    image: postgres:16
    build:
      context: .
    container_name: postgres_db
    environment:
      POSTGRES_USER: casesuser
      POSTGRES_PASSWORD: casespassword321
      POSTGRES_DB: casesdb
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres: